### ISSUE TITLE
Handle unknown keys more gracefully

### ISSUE THREAD

**Issue by reynir** [mirage/awa-ssh#57]
When a client connects with an unknown key type (e.g. ECDSA) to an awa-ssh server the server doesn't recognize the key type and gives up parsing. It would be more graceful if the server handles unknown keys by informing the client that the provided key isn't accepted.

**Comment by hannesm** [comment]
at the same time, would it be worth to add more KEX to the server implementation? I can do that for you, or together with you, if you like :)

**Comment by hannesm** [comment]
The ECDH key exchange algorithms are supported in #63 for the server. Still, only ED25519 and RSA hostkeys (client keys) - so I will leave this open.

**Comment by hannesm** [comment]
done with #68
