### ISSUE TITLE
awa-lwt rekey issue

### ISSUE THREAD

**Issue by reynir** [mirage/awa-ssh#60]
Same issue as in #58.

**Comment by hannesm** [comment]
this is not an issue, since in awa-lwt, `Lwt.pick` is used (and the timeout is cancelled when some other promise is fulfilled).

**Comment by palainp** [comment]
This is just a minor comment to explain why `Lwt.nchoose_split` is used (and not `Lwt.pick`) in awa-mirage: I had some issues when the timeout is triggered and there is still something to handle on the network side (which is overridden by the timeout) (e.g. https://github.com/mirage/awa-ssh/pull/35#issuecomment-956005503).
